### ISSUE TITLE
Logo proposal for Campfire

### ISSUE THREAD

**Issue by CallMeFib3r** [pandulapeter/campfire-backend#1]
Hi @pandulapeter ,
I came up with a logo/icon for to your android app. With your permission I'd like to present it to you and if necessary adjust it to your personal preference.
This is my initial draft. 

![campfire-02](https://user-images.githubusercontent.com/37731582/40299212-d962d8c8-5ce5-11e8-8e19-910dbd6fc4fa.png)

Could you let me know what you think?
Kind regards,

Fiber

**Comment by pandulapeter** [comment]
Hi Fiber!

This is very kind of you, and I actually really like the idea! It's a lot more original than the one I'm currently using.

At the moment I'm working on the final touches for the initial version of Campfire and while the first version of Material Design that I tried to follow is slowly becoming outdated, my main focus at the moment is creating content for the app.

That being said, I'm planning to do a larger redesign after the public launch and I've already asked around for professional help as I'm not really qualified to do this. If we were to use your idea (or a modified version of it) for the app's icon, what are your conditions? I'd be more than happy to give credit for your work in the app's About section. Anyway, I'll definitely contact you when polishing the design becomes a priority.

Thanks again for your proposal and your interest in Campfire! If you'd like to give the app a try, feel free to join [this Google+ community](https://plus.google.com/communities/104615840487719249096?sqinv=SVFINUg1WlM4cTdqVWwtc2sxSllsU0xUSUpDd2xn) and become an alpha tester. After you join, follow the link in the first post to get to the Play Store listing.

Peter

**Comment by CallMeFib3r** [comment]
Hi Peter,

I'm glad to hear that you like my design. My conditions are quite simple, the logo is completely free of charge and I will provide all the files you would ever need as well as editable files (if you would want to change it up in the future). I will also provide a license that gives you all the rights.

I'm getting rewarded by an open source platform called Utopian (www.utopian.io) ( that stimulates designers like myself to go out and support open source projects (like yours). It's certainly worth checking out.

When you are ready for a public release you can hit me up again and we can go from there.

Kind regards,

Fiber

**Comment by pandulapeter** [comment]
This is the first time I hear about Utopian but it looks awesome! Thanks again, I'll be in touch :)
